#!/usr/bin/groovy

def app ="app.apk"
def token ="

pipeline {
	agent any
	options {
        	disableConcurrentBuilds()
    	}
	environment {
		PYTHONPATH = "${WORKSPACE}"
	}
   	stages {
        	stage("Deploy - Mobsf") {
            		steps { deploy('mobsf') }
		}
	}
	stages {
        	stage("Upload APK") {
            		steps { upload() }
		}
	}
}

def deploy(environment) {

	def containerName = ''
	def port = ''

	if ("${environment}" == 'mobsf') {
		containerName = "mobsf"
		port = "8000"
	} 
	else {
		println "Environment not valid"
		System.exit(0)
	}

	sh "docker ps -f name=${containerName} -q | xargs --no-run-if-empty docker stop"
	sh "docker ps -a -f name=${containerName} -q | xargs -r docker rm"
	sh "docker run -d -p ${port}:8000 --name ${containerName} opensecurity/mobile-security-framework-mobsf:latest"

}

def upload() {

	sh "curl -F 'file=@$app' http://localhost:8000/api/v1/upload -H "Authorization:$token"
}
